// Created with resguy v9 (September 2018)
// https://github.com/wootguy/resguy

gfx/env/sky_byblo02_01bk.tga
gfx/env/sky_byblo02_01dn.tga
gfx/env/sky_byblo02_01ft.tga
gfx/env/sky_byblo02_01lf.tga
gfx/env/sky_byblo02_01rt.tga
gfx/env/sky_byblo02_01up.tga
models/bman/bman_powerup_a.mdl
models/bman/bomb_antidelay_a.mdl
models/bman/bomb_bronze_a.mdl
models/bman/bomb_gold_a.mdl
models/bman/bomb_large_b.mdl
models/bman/bomb_med_b.mdl
models/bman/bomb_silver_a.mdl
models/bman/bomb_small_b.mdl
models/player/bman_black/bman_black.bmp
models/player/bman_black/bman_black.mdl
models/player/bman_pink/bman_pink.bmp
models/player/bman_pink/bman_pink.mdl
models/player/bman_white/bman_white.bmp
models/player/bman_white/bman_white.mdl
sound/bman/aaaa.wav
sound/bman/draw.mp3
sound/bman/finished.mp3
sound/bman/item_get.mp3
sound/bman/kick.mp3
sound/bman/lead.mp3
sound/bman/podium.mp3
sound/bman/round.mp3
sound/bman/round2.mp3
sound/bman/round3.mp3
sound/bman/skull.mp3
sound/bman/tick.wav
sound/bman/winrar.mp3
sprites/bman/bonus_bomb2.spr
sprites/bman/bonus_bomb3.spr
sprites/bman/bonus_life.spr
sprites/rc/rc_explosion2HD.spr
sprites/rc/rc_explosionHD.spr
